import React, { ReactNode, useEffect } from 'react';
import { ArrowRight, Check, Copy, WarningCircle, X } from '@phosphor-icons/react';

export const DoubleBezel = ({ children, className = '', innerClassName = '' }: { children: ReactNode; className?: string; innerClassName?: string }) => <div className={`bezel ${className}`}><div className={`bezel-core ${innerClassName}`}>{children}</div></div>;

export const PageHeader = ({ label, title, body, actions }: { label?: string; title: string; body?: string; actions?: ReactNode }) => <header className="page-enter flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div className="max-w-3xl">{label && <p className="eyebrow mb-3">{label}</p>}<h1 className="display-title font-serif font-semibold">{title}</h1>{body && <p className="mt-4 max-w-[65ch] text-base leading-relaxed text-muted-ink">{body}</p>}</div>{actions && <div className="flex shrink-0 flex-wrap gap-3">{actions}</div>}</header>;

export const PrimaryButton = ({ children, icon = <ArrowRight />, className = '', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { icon?: ReactNode }) => <button className={`btn-primary group ${className}`} {...props}><span>{children}</span>{icon && <span className="icon-island">{icon}</span>}</button>;
export const SkeletonBlock = ({ className = '' }: { className?: string }) => <div aria-hidden="true" className={`skeleton rounded-2xl ${className}`} />;
export const InlineError = ({ message, onRetry }: { message: string; onRetry?: () => void }) => <div role="alert" className="flex items-center justify-between gap-4 rounded-2xl bg-danger-light p-4 text-sm text-danger ring-1 ring-danger/20"><span className="flex items-center gap-2"><WarningCircle size={20} weight="light" />{message}</span>{onRetry && <button onClick={onRetry} className="font-semibold underline underline-offset-4">Retry</button>}</div>;
export const EmptyState = ({ title, body, action }: { title: string; body: string; action?: ReactNode }) => <div className="py-16 text-center"><div className="mx-auto mb-5 flex h-14 w-14 items-center justify-center rounded-2xl bg-teal-light text-teal"><Check size={26} weight="light" /></div><h2 className="text-3xl font-semibold">{title}</h2><p className="mx-auto mt-3 max-w-md text-muted-ink">{body}</p>{action && <div className="mt-6">{action}</div>}</div>;

export const HashValue = ({ value }: { value: string }) => { const [copied, setCopied] = React.useState(false); const copy = async () => { await navigator.clipboard.writeText(value); setCopied(true); window.setTimeout(() => setCopied(false), 1200); }; return <button onClick={copy} className="group flex max-w-full items-center gap-2 font-mono text-[11px] text-muted-ink" title="Copy hash"><span className="truncate">{value}</span>{copied ? <Check size={15} /> : <Copy size={15} />}</button>; };

export const ConfirmAction = ({ open, title, body, confirmLabel, onConfirm, onClose, busy = false }: { open: boolean; title: string; body: string; confirmLabel: string; onConfirm: () => void; onClose: () => void; busy?: boolean }) => { useEffect(() => { const fn = (e: KeyboardEvent) => e.key === 'Escape' && onClose(); if (open) document.addEventListener('keydown', fn); return () => document.removeEventListener('keydown', fn); }, [open, onClose]); if (!open) return null; return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-ink/55 p-4" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><DoubleBezel className="w-full max-w-lg" innerClassName="p-7"><div className="flex items-start justify-between gap-5"><div><p className="eyebrow mb-2">Critical action</p><h2 id="confirm-title" className="text-3xl font-semibold">{title}</h2></div><button onClick={onClose} className="flex h-11 w-11 items-center justify-center rounded-full bg-canvas" aria-label="Close confirmation"><X size={20} /></button></div><p className="mt-4 leading-relaxed text-muted-ink">{body}</p><div className="mt-7 flex justify-end gap-3"><button className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-danger" disabled={busy} onClick={onConfirm}>{busy ? 'Working…' : confirmLabel}</button></div></DoubleBezel></div>; };
