# Generated by Django 5.1.15 on 2026-08-01 17:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0002_principal_credit_pool_ceiling'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scenario_key', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='READY', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('initial_state', models.JSONField(default=dict)),
                ('final_state', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_sessions', to='identity.agent')),
            ],
        ),
        migrations.CreateModel(
            name='DemoStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('actor', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=120)),
                ('endpoint', models.CharField(blank=True, default='', max_length=255)),
                ('transport_status', models.PositiveIntegerField(default=200)),
                ('semantic_result', models.CharField(max_length=40)),
                ('plain_language', models.TextField()),
                ('proof', models.TextField()),
                ('request_evidence', models.JSONField(default=dict)),
                ('response_evidence', models.JSONField(default=dict)),
                ('balance_before', models.JSONField(default=dict)),
                ('balance_after', models.JSONField(default=dict)),
                ('gateway_checks', models.JSONField(default=list)),
                ('audit_sequence', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='demo.demosession')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('session', 'sequence'), name='unique_demo_session_step')],
            },
        ),
    ]
