# Generated by Django 5.1.15 on 2026-08-01 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gateway", "0001_initial"),
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepaymentSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("PROCESSING", "Processing"),
                            ("SETTLED", "Settled"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "draw",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayment_schedules",
                        to="gateway.drawrequest",
                    ),
                ),
                (
                    "linked_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repayment_schedules",
                        to="identity.linkedaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepaymentAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount_pulled", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("INSUFFICIENT_FUNDS", "Insufficient Funds"),
                            ("ACCOUNT_BLOCKED", "Account Blocked"),
                            ("MANDATE_INVALID", "Mandate Invalid"),
                            ("PROVIDER_ERROR", "Provider Error"),
                        ],
                        max_length=50,
                    ),
                ),
                ("bank_transaction_ref", models.CharField(max_length=100)),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="repayment.repaymentschedule",
                    ),
                ),
            ],
        ),
    ]
