# Generated by Django 5.1.15 on 2026-08-01 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorityStateTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("previous_state", models.CharField(max_length=50)),
                ("next_state", models.CharField(max_length=50)),
                ("trigger_code", models.CharField(max_length=100)),
                ("reason", models.TextField()),
                ("actor_type", models.CharField(default="SYSTEM", max_length=50)),
                ("actor_id", models.CharField(default="SYSTEM", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_transitions",
                        to="identity.agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Escalation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("trigger_code", models.CharField(max_length=100)),
                ("severity", models.CharField(default="HIGH", max_length=50)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_REVIEW", "In Review"),
                            ("RESOLVED", "Resolved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="OPEN",
                        max_length=50,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="identity.agent",
                    ),
                ),
            ],
        ),
    ]
