# Generated by Django 5.1.15 on 2026-08-01 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustedReceiptIssuer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("public_key_b64", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RiskProfileSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weighted_risk_score",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "identity_confidence",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    "task_reliability",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    "repayment_reliability",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    "spending_regularity",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    "current_exposure_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "current_exposure_utilization",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("repayment_imputed", models.BooleanField(default=True)),
                ("spending_imputed", models.BooleanField(default=True)),
                ("ahp_version", models.CharField(default="v1.0", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_snapshots",
                        to="identity.agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RiskComponentEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("component", models.CharField(max_length=50)),
                ("score", models.DecimalField(decimal_places=4, max_digits=5)),
                ("evidence_count", models.IntegerField(default=0)),
                ("source", models.CharField(max_length=255)),
                ("is_imputed", models.BooleanField(default=False)),
                ("reason", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_items",
                        to="risk.riskprofilesnapshot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "expected_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="identity.agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("outcome", models.CharField(max_length=50)),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("issued_at", models.DateTimeField()),
                ("nonce", models.CharField(max_length=64, unique=True)),
                ("ed25519_signature", models.CharField(max_length=255)),
                ("consumed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="identity.agent",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="risk.task",
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="risk.trustedreceiptissuer",
                    ),
                ),
            ],
        ),
    ]
