# Generated by Django 5.1.15 on 2026-08-01 09:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("sequence", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "event_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("actor_type", models.CharField(max_length=50)),
                ("actor_id", models.CharField(max_length=255)),
                ("entity_type", models.CharField(max_length=100)),
                ("entity_id", models.CharField(max_length=255)),
                ("payload", models.JSONField()),
                ("payload_hash", models.CharField(max_length=64)),
                ("previous_hash", models.CharField(max_length=64)),
                ("current_hash", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
    ]
