# Generated by Django 5.1.15 on 2026-08-01 09:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_credit_limit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("2000.00"), max_digits=12
                    ),
                ),
                (
                    "target_credit_limit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("2000.00"), max_digits=12
                    ),
                ),
                (
                    "cold_start_floor",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("2000.00"), max_digits=12
                    ),
                ),
                (
                    "principal_authorized_ceiling",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("15000.00"), max_digits=12
                    ),
                ),
                (
                    "reserved_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "outstanding_principal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_account",
                        to="identity.agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditLimitChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "previous_limit",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("target_limit", models.DecimalField(decimal_places=2, max_digits=12)),
                ("new_limit", models.DecimalField(decimal_places=2, max_digits=12)),
                ("alpha", models.DecimalField(decimal_places=2, max_digits=4)),
                ("trigger", models.CharField(max_length=100)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "credit_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="limit_changes",
                        to="credit.creditaccount",
                    ),
                ),
            ],
        ),
    ]
