# Generated by Django 5.1.15 on 2026-08-01 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("credit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("request_hash", models.CharField(max_length=64)),
                ("response_status", models.IntegerField()),
                ("response_body", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DrawRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("merchant_name", models.CharField(max_length=255)),
                ("merchant_category", models.CharField(max_length=100)),
                ("idempotency_key", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("RESERVED", "Reserved"),
                            ("SETTLING", "Settling"),
                            ("SETTLED", "Settled"),
                            ("REJECTED", "Rejected"),
                            ("REVOKED", "Revoked"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="REQUESTED",
                        max_length=50,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credit_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draw_requests",
                        to="credit.creditaccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DrawReservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reserved_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("expires_at", models.DateTimeField()),
                ("status", models.CharField(default="HELD", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draw_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation",
                        to="gateway.drawrequest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entry_type", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "running_outstanding_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "credit_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="credit.creditaccount",
                    ),
                ),
                (
                    "draw_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="gateway.drawrequest",
                    ),
                ),
            ],
        ),
    ]
