# Generated by Django 5.1.15 on 2026-08-01 09:29

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("purpose", models.TextField(blank=True, default="")),
                ("api_key_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(db_index=True, default="NORMAL", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LinkedAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_reference", models.CharField(max_length=100, unique=True)),
                (
                    "bank_name",
                    models.CharField(
                        default="TrustLine Simulated Bank", max_length=100
                    ),
                ),
                ("status", models.CharField(default="ACTIVE", max_length=50)),
                (
                    "mock_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("50000.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Principal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CapabilityManifest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("allowed_categories", models.JSONField(default=list)),
                ("denied_categories", models.JSONField(default=list)),
                (
                    "max_per_transaction",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5000.00"), max_digits=12
                    ),
                ),
                (
                    "max_per_day",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("20000.00"), max_digits=12
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=10)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("manifest_version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manifests",
                        to="identity.agent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mandate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("manifest_hash", models.CharField(max_length=64)),
                (
                    "authorized_ceiling",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("ed25519_signature", models.CharField(max_length=255)),
                ("public_key_b64", models.CharField(max_length=255)),
                ("issued_at", models.DateTimeField()),
                ("not_before", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("nonce", models.CharField(max_length=64, unique=True)),
                ("version", models.IntegerField(default=1)),
                ("is_revoked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandates",
                        to="identity.agent",
                    ),
                ),
                (
                    "linked_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandates",
                        to="identity.linkedaccount",
                    ),
                ),
                (
                    "principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandates",
                        to="identity.principal",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agent",
            name="current_mandate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_agents",
                to="identity.mandate",
            ),
        ),
        migrations.AddField(
            model_name="linkedaccount",
            name="principal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_accounts",
                to="identity.principal",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="principal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agents",
                to="identity.principal",
            ),
        ),
        migrations.CreateModel(
            name="PrincipalVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(default="MOCK_OAUTH", max_length=100)),
                ("provider_subject_id", models.CharField(max_length=255)),
                (
                    "verification_level",
                    models.CharField(default="VERIFIED_HIGH", max_length=50),
                ),
                ("status", models.CharField(default="VERIFIED", max_length=50)),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "principal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="identity.principal",
                    ),
                ),
            ],
        ),
    ]
